MUSIC_PATH_NAME: '/mnt/music'
DAEMON_USER: 'sergey'
DAEMON_GROUP: 'sergey'
DEBUG: false
LOGGING_LEVEL: 'DEBUG'
PID_FILE_COMMANDER: '/var/run/cdp-sa/commander.pid'
PID_FILE_PLAYBACK: '/var/run/cdp-sa/player.pid'
PID_FILE_RIPPING: '/var/run/cdp-sa/ripping.pid'
PID_FILE_REMOTE_CONTROL: '/var/run/cdp-sa/remote-control.pid'
PID_FILE_DISPLAY: '/var/run/cdp-sa/display.pid'
LOG_FILE_COMMANDER: '/var/log/cdp-sa/commander.log'
LOG_FILE_PLAYBACK: '/var/log/cdp-sa/playback.log'
LOG_FILE_RIPPING: '/var/log/cdp-sa/ripping.log'
LOG_FILE_REMOTE_CONTROL: '/var/log/cdp-sa/remote-control.log'
LOG_FILE_DISPLAY: '/var/log/cdp-sa/display.log'
